version: "3.8"
services:
  web:
    image: processmaker/pm4-core:${PM_VERSION}
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
    environment:
      - PM_APP_URL
      - PM_APP_PORT
      - PM_BROADCASTER_PORT
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - proc_m_storage:/code/pm4/storage
    links:
      - redis
      - mysql 
    depends_on:
      - mysql
      - redis 
  redis:
    image: redis
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: processmaker
      MYSQL_USER: pm
      MYSQL_PASSWORD: pass
    volumes:
      - proc_m_database:/var/lib/mysql
volumes:
  proc_m_database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/sherlock/Code/genesis_project/the_architect/process_manager/process_manager_data/database'
  proc_m_storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/sherlock/Code/genesis_project/the_architect/process_manager/process_manager_data/storage'